from models import AuditResult, Issue, SeverityBreakdown


def get_demo_audit_result() -> AuditResult:
    return DEMO_SCENARIOS[0]


DEMO_SCENARIOS = [
    AuditResult(
        model_score=48,
        summary="Detected 7 issue(s). Model risk is high risk, with 1 critical, 3 high, 3 medium, and 0 low severity finding(s).",
        severity_breakdown=SeverityBreakdown(critical=1, high=3, medium=3, low=0),
        issues=[
            Issue(
                id="demo_growth_ref_error",
                severity="critical",
                sheet="Forecast",
                cell="H42",
                category="Formula Error",
                title="Formula error #REF!",
                description="Cell H42 contains Excel error value #REF! in the revenue forecast.",
                why_it_matters="Broken revenue formulas can flow into EBITDA, cash flow, and valuation outputs.",
                suggested_fix="Trace precedent cells and restore the deleted or moved reference.",
            ),
            Issue(
                id="demo_revenue_growth",
                severity="high",
                sheet="Forecast",
                cell="F12",
                category="Business Logic",
                title="Suspicious revenue growth",
                description="Revenue grows by 137% from E12 to F12.",
                why_it_matters="A step change above 100% needs clear commercial support or it may overstate valuation.",
                suggested_fix="Validate bookings, pricing, customer count, and ramp assumptions behind the growth.",
            ),
            Issue(
                id="demo_external_link",
                severity="high",
                sheet="Forecast",
                cell="D18",
                category="External Links",
                title="External workbook link",
                description="Formula references [Board_Plan_2025.xlsx].",
                why_it_matters="External links can break or make the model impossible to reproduce.",
                suggested_fix="Import the source data or package the linked workbook with the model.",
            ),
            Issue(
                id="demo_hidden_sheet",
                severity="high",
                sheet="Mgmt Overrides",
                cell="",
                category="Hidden Content",
                title="Hidden worksheet detected",
                description="Worksheet 'Mgmt Overrides' is hidden.",
                why_it_matters="Hidden override sheets can materially alter outputs without reviewer visibility.",
                suggested_fix="Unhide the sheet and document each override.",
            ),
            Issue(
                id="demo_formula_constant",
                severity="medium",
                sheet="Forecast",
                cell="G27",
                category="Formula Integrity",
                title="Hardcoded constant inside formula",
                description="Formula '=G26*1.35' contains a hardcoded growth assumption.",
                why_it_matters="Hardcoded assumptions are difficult to audit and update consistently.",
                suggested_fix="Move 35% growth to the assumptions sheet and reference it.",
            ),
            Issue(
                id="demo_margin_jump",
                severity="medium",
                sheet="Forecast",
                cell="F31",
                category="Business Logic",
                title="Suspicious margin jump",
                description="Gross margin changes by 24 percentage points from E31 to F31.",
                why_it_matters="Large margin jumps can materially distort profitability.",
                suggested_fix="Confirm COGS, mix, and operating leverage assumptions.",
            ),
            Issue(
                id="demo_empty_assumption",
                severity="medium",
                sheet="Assumptions",
                cell="A15",
                category="Assumptions",
                title="Empty assumption line",
                description="Assumption row 'Churn rate' has no entered values.",
                why_it_matters="Missing assumptions can cause formulas to rely on blanks or unintended zero values.",
                suggested_fix="Populate churn assumptions for each forecast period.",
            ),
        ],
    ),
    AuditResult(
        model_score=72,
        summary="Detected 4 issue(s). Model risk is moderate risk, with 0 critical, 1 high, 2 medium, and 1 low severity finding(s).",
        severity_breakdown=SeverityBreakdown(critical=0, high=1, medium=2, low=1),
        issues=[
            Issue(
                id="demo_cash_flow",
                severity="high",
                sheet="Cash Flow",
                cell="I35",
                category="Business Logic",
                title="Negative running cash flow",
                description="Running cash flow turns negative in the downside case.",
                why_it_matters="Negative cash flow may imply a funding gap or missing financing assumption.",
                suggested_fix="Review working capital, capex, and debt draw assumptions.",
            ),
            Issue(
                id="demo_hidden_column",
                severity="medium",
                sheet="Debt Schedule",
                cell="K",
                category="Hidden Content",
                title="Hidden column detected",
                description="Column K is hidden.",
                why_it_matters="Hidden columns may contain helper calculations or manual adjustments.",
                suggested_fix="Unhide and review the column before distribution.",
            ),
            Issue(
                id="demo_inconsistent_formula",
                severity="medium",
                sheet="Debt Schedule",
                cell="J22",
                category="Formula Integrity",
                title="Inconsistent neighboring formula",
                description="Formula in J22 differs from adjacent debt amortization formulas.",
                why_it_matters="Formula inconsistencies can create silent forecast errors.",
                suggested_fix="Copy the intended formula pattern across the forecast period.",
            ),
            Issue(
                id="demo_review_note",
                severity="low",
                sheet="Summary",
                cell="B6",
                category="Presentation",
                title="Stale review date",
                description="The model review date predates the latest forecast period.",
                why_it_matters="Stale documentation makes it harder to confirm model governance.",
                suggested_fix="Update the review date and owner before sharing.",
            ),
        ],
    ),
    AuditResult(
        model_score=91,
        summary="Detected 2 issue(s). Model risk is mostly sound, with 0 critical, 0 high, 1 medium, and 1 low severity finding(s).",
        severity_breakdown=SeverityBreakdown(critical=0, high=0, medium=1, low=1),
        issues=[
            Issue(
                id="demo_assumption_gap",
                severity="medium",
                sheet="Assumptions",
                cell="A9",
                category="Assumptions",
                title="Empty assumption line",
                description="Assumption row 'Terminal growth' has no entered values.",
                why_it_matters="Missing terminal assumptions can leave valuation formulas incomplete or defaulted.",
                suggested_fix="Add terminal growth assumptions or remove the unused valuation section.",
            ),
            Issue(
                id="demo_hidden_row",
                severity="low",
                sheet="Operating Model",
                cell="44",
                category="Hidden Content",
                title="Hidden row detected",
                description="Row 44 is hidden.",
                why_it_matters="Hidden rows can obscure inactive calculations or old model logic.",
                suggested_fix="Unhide the row and remove it if it is no longer needed.",
            ),
        ],
    ),
]
